### ISSUE TITLE
Settings Button bug, endless repitition

### ISSUE THREAD

**Issue by lasurakswarm** [TylerBlakeslee/Aca#27]
Tapping the settings button repeatedly will repeatedly open the same activity without a possible way of ending it. The bug can go until it it's been too many times and the app will crash. As a fix, a dialog could pop up, or the button could just disappear while it's on the Settings activity.

**Comment by TylerBlakeslee** [comment]
Fixed by commenting out code so when user is on Settings and Song List page respectively, another version of the page is not loaded.
